[tool.poetry]
name = "hw27"
version = "0.1.0"
description = ""
authors = ["dariglad <DariGlad>"]


[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
